pipeline {
    agent any

    triggers {
        pollSCM '*/5 * * * *'
    }

    environment {
        DOCKER_CREDENTIALS_ID = 'proj-jenkins'
        GITHUB_REPO = 'https://github.com/ayusao/VIZUO.git'
        DOCKER_IMAGE = "vizuo:latest"
    }

    stages {
        stage('Checkout') {
            steps {
                script {
                    echo "Cloning the repository from GitHub..."
                    git branch: 'main', credentialsId: "${DOCKER_CREDENTIALS_ID}", url: "${GITHUB_REPO}"
                }
            }
        }

        stage('Build and Push') {
            steps {
                script {
                    echo "Building Docker image..."
                    sh 'docker build -t $DOCKER_IMAGE .'
                    
                    echo "Pushing Docker image..."
                    sh 'docker push $DOCKER_IMAGE'
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                script {
                    echo "Deploying to Kubernetes..."
                    sh 'kubectl apply -f deployment.yaml'
                    sh 'kubectl rollout restart deployment vizuo-app'
                }
            }
        }
    }

    post {
        success {
            echo "CI/CD Pipeline completed successfully!"
        }
        failure {
            echo "CI/CD Pipeline failed!"
        }
    }
}